"""Generate a report config tailored to exact mask + WSI paths.

Usage:
    python make_report_config.py \
        --masks /path/to/masks_dir \
        --wsi-root /mnt/bioptic_tree \
        --out /path/to/output_dir \
        [--title "My Report"]

WSI path is generated from slide name:
    {wsi-root}/{year}/{month}/{day}/{slide_name}/{slide_name}.mrxs
e.g. slide 2023_04052-1-N -> /mnt/bioptic_tree/2023/04/052/2023_04052-1-N/2023_04052-1-N.mrxs

Writes: <out>/report_conf/reporter/region_clustering.yaml
"""
import argparse
from pathlib import Path

TEMPLATE = """\
# Auto-generated by make_report_config.py
# Masks: {masks_dir}
# WSI root: {wsi_root}
# Slides: {n_slides}

defaults:
  - _self_

title: {title}

background:
  _target_: report.masks.BasicImageRetriever
  source_dir: {wsi_root}
  globs:
{globs}
  layer_name: WSI

mask_retrievers:
  - _target_: report.masks.DriveMasksRetriever
    dir_name: {masks_dir}
    layer_name: Region Clusters
    shader_conf:
      type: colormap
      params:
        use_channel0: r
        opacity: 0.55
        connect:
          type: bool
          interactive: false
          default: true
        color:
          type: custom_colormap
          default:
{colormap}
          steps: {n_colors}
          mode: qualitative
          interactive: true
          title: 'Colormap:'
          continuous: false
        threshold:
          breaks:
{breaks}
          mask:
{mask_vals}
          interactive: false
          inverted: true
          maskOnly: true
          toggleMask: true
          title: Categories
          min: 0
          max: 1
          minGap: 0.021505
          step: null
          pips:
            mode: count
            values: {n_colors}
            density: 4
            stepped: true

save:
  _target_: report.save.MLFlowReportStorer
  artifact_path: report.html
  metadata:
    experiment_name: Breast Cancer
    run_name: {title}
    description: Region cluster masks overlaid on WSIs
    user: ${{user}}
"""

# 32-color palette (same as before)
PALETTE = [
    "", "#A64630", "#F4A87B", "#A67230", "#F4D67B", "#A69F30", "#E5F47B",
    "#81A630", "#B8F47B", "#55A630", "#8AF47B", "#30A638", "#7BF499",
    "#30A664", "#7BF4C7", "#30A690", "#7BF4F4", "#3090A6", "#7BC7F4",
    "#3064A6", "#7B99F4", "#3038A6", "#8A7BF4", "#5530A6", "#B87BF4",
    "#8130A6", "#E57BF4", "#A6309F", "#F47BD6", "#A63072", "#F47BA8",
    "#A63046", "#4630A6",
]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--masks", required=True, help="dir with .tiff mask files")
    ap.add_argument("--wsi-root", required=True, help="root of bioptic tree (e.g. /mnt/bioptic_tree)")
    ap.add_argument("--out", required=True, help="output dir for report_conf/")
    ap.add_argument("--title", default="Region Clustering")
    args = ap.parse_args()

    masks_dir = Path(args.masks)
    wsi_root = Path(args.wsi_root)

    # mask files -> slide names (stem)
    mask_files = sorted(masks_dir.glob("*.tiff"))
    if not mask_files:
        raise SystemExit(f"no .tiff files in {masks_dir}")

    # generate relative WSI paths from slide names
    # slide name like 2023_04052-1-N -> 2023/04/052/2023_04052-1-N/2023_04052-1-N.mrxs
    globs_list = []
    missing = []
    for f in mask_files:
        name = f.stem
        # parse: YYYY_MMDDD-suffix
        year = name[:4]
        month = name[5:7]
        day = name[7:10]
        rel = f"{year}/{month}/{day}/{name}/{name}.mrxs"
        full = wsi_root / rel
        if full.exists():
            globs_list.append(rel)
        else:
            missing.append(name)

    if not globs_list:
        raise SystemExit(f"no WSI files found under {wsi_root} for {len(mask_files)} masks")
    if missing:
        print(f"[warn] {len(missing)} WSIs not found, e.g. {missing[:5]}")
    print(f"{len(globs_list)}/{len(mask_files)} slides matched")

    # build globs list (relative paths work with rglob)
    globs = "\n".join(f'    - "{g}"' for g in sorted(globs_list))

    # colormap entries
    n_colors = len(PALETTE)
    colormap = "\n".join(f"          - '{c}'" for c in PALETTE)

    # threshold breaks (n_colors values from 1/255 to n/255)
    breaks = "\n".join(f"          - {i / 255:.6f}" for i in range(1, n_colors + 1))
    mask_vals = "\n".join(f"          - {1 if i > 0 else 0}" for i in range(n_colors + 1))

    cfg = TEMPLATE.format(
        masks_dir=str(masks_dir),
        wsi_root=str(wsi_root),
        n_slides=len(globs_list),
        title=args.title,
        globs=globs,
        colormap=colormap,
        n_colors=n_colors + 1,
        breaks=breaks,
        mask_vals=mask_vals,
    )

    dest = Path(args.out) / "report_conf" / "reporter" / "region_clustering.yaml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(cfg)
    print(f"wrote: {dest}")


if __name__ == "__main__":
    main()
