# @package _global_

mlflow_artifact_path: tiling
tile_size: ???
stride: ???

metadata:
  run_name: Tiling ${dataset.name}
  description: ???
  hyperparams:
    tile_size: ${tile_size}
    stride: ${stride}

