# @package _global_

level: ??? # TODO: set, for marojiry of projects levels 3 to 5 should be a good choice
max_concurrent: 8
mlflow_artifact_path: tissue_masks

metadata:
  run_name: Tissue Masks ${dataset.name}
  hyperparams:
    level: ${level}

